// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BDfS6VIN3jLh29TUsSEx0rSs4u34fBA',
    appId: '1:593193795822:web:0d69e1286b32d9269fb3ff',
    messagingSenderId: '593193795822',
    projectId: 'e-book-cffd6',
    authDomain: 'e-book-cffd6.firebaseapp.com',
    storageBucket: 'e-book-cffd6.firebasestorage.app',
    measurementId: 'G-LRXNFYZXB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDcb23KpRs2wRqqlGUiI6tmQC6kQyA1Y',
    appId: '1:593193795822:android:bebc74a846ebb5109fb3ff',
    messagingSenderId: '593193795822',
    projectId: 'e-book-cffd6',
    storageBucket: 'e-book-cffd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7Vm6NrZ33yUyAzGgqAo4ctkKAiunPEs',
    appId: '1:593193795822:ios:af2a61fa3af7b3549fb3ff',
    messagingSenderId: '593193795822',
    projectId: 'e-book-cffd6',
    storageBucket: 'e-book-cffd6.firebasestorage.app',
    iosBundleId: 'com.example.ebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD7Vm6NrZ33yUyAzGgqAo4ctkKAiunPEs',
    appId: '1:593193795822:ios:af2a61fa3af7b3549fb3ff',
    messagingSenderId: '593193795822',
    projectId: 'e-book-cffd6',
    storageBucket: 'e-book-cffd6.firebasestorage.app',
    iosBundleId: 'com.example.ebookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-BDfS6VIN3jLh29TUsSEx0rSs4u34fBA',
    appId: '1:593193795822:web:e6dbbe34f767702c9fb3ff',
    messagingSenderId: '593193795822',
    projectId: 'e-book-cffd6',
    authDomain: 'e-book-cffd6.firebaseapp.com',
    storageBucket: 'e-book-cffd6.firebasestorage.app',
    measurementId: 'G-CG5X8TEE2P',
  );
}
